### 將MNIST的資料載入，並且進行標準化(normalization)
~~~
MNIST是一個手寫數字的資料包，分成訓練資料(training data)與測試資料(testing data)，x為圖片、y為所對應數字。
載入的x為大小為28*28的圖片共60000張，且每個像素的數值介於0~255之間，標準化後介於0~1之間。
載入的y為所對應的數字0~9，運用keras中的np_utils.to_categorical將y轉成one-hot的形式，轉為一個10維的vector
~~~

In [33]:
from keras.datasets import mnist
from keras.utils import np_utils

# 載入minst的資料
(X_train,Y_train),(X_test,Y_test) = mnist.load_data()

# 將圖片轉換為一個60000*784的向量，並且標準化
X_train = X_train.reshape(X_train.shape[0],28*28)
X_test = X_test.reshape(X_test.shape[0],28*28)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train = X_train / 255
X_test = X_test / 255

# 將y轉換成one-hot encoding
Y_train = np_utils.to_categorical(Y_train,10)
Y_test= np_utils.to_categorical(Y_test,10)

print (X_train,Y_train)
print (X_test,Y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 搭建神經網路以DNN (deep neural network) 作為範例
~~~
Keras的核心為模型，最主要也是最常使用的是Sequential這個模型，Sequential可以按照順序的將神經網路串起。
運用.add()可以一層一層的將神經網路疊起。在每一層之中只需要簡單的設定每層的大小(units)與激活函數(activation function)。
PS. 
1. 第一層要記得寫輸入的向量大小、最後一層的units要等於輸出的向量大小
2. 最後一層使用的激活函數(activation function)為softmax
~~


In [39]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation
from keras.optimizers import Adam

model = Sequential()
model.add(Dense(input_dim=28*28,units=500,activation='relu'))
model.add(Dense(units=500,activation='relu'))
model.add(Dense(units=500,activation='relu'))
model.add(Dense(units=10,activation='softmax'))
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_13 (Dense)             (None, 500)               392500    
_________________________________________________________________
dense_14 (Dense)             (None, 500)               250500    
_________________________________________________________________
dense_15 (Dense)             (None, 500)               250500    
_________________________________________________________________
dense_16 (Dense)             (None, 10)                5010      
Total params: 898,510
Trainable params: 898,510
Non-trainable params: 0
_________________________________________________________________
